### ISSUE TITLE
Error: `by` required, because the data sources have no common variables

### ISSUE THREAD

**Issue by duttashi** [duttashi/text-analysis#4]
I was using the `anti_join` function to remove stop words from the text data. The initial code was like the following;
`clean_novel <- wuthering_heights %>%
   anti_join(stop_words)`

To find the problem, I used the `traceback()` function from the base r and found the problem was at line `13`

`16: stop(cnd)
15: .abort(text)
14: glubort(fmt_args(args), ..., .envir = .envir)
13: bad_args("by", "required, because the data sources have no common variables")
12: common_by.NULL(by, x, y)
11: common_by(by, x, y)
10: anti_join.tbl_df(., stop_words)
9: anti_join(., stop_words)
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(expr, envir, enclos)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: wuthering_heights %>% anti_join(stop_words)`

**Comment by duttashi** [comment]
The `wuthering_heights` tibble had a list of words under the column named, `text` and the stop_words data frame had a list of words under the column named, `word`. however, the columns are inverted: in stop_words, it's the first column, while in my dataset it's the second column. That's why the command is unable to "match" the two columns and compare the words. Try this:
`tidy_novel_data <- wuthering_heights %>%
  anti_join(stop_words, by=c("text"="word"))`

And it now works :-)

**Comment by jenyagoncharov** [comment]
Thanks! this was helpful to me.
