### ISSUE TITLE
Warning: In wordcloud, word could not be fit on page. It will not be plotted- Using RStudio

### ISSUE THREAD

**Issue by duttashi** [duttashi/text-analysis#5]
This warning is generated if the plot size is small.

**Comment by duttashi** [comment]
Solution: Either increase the plotting window size in RStudio or decrease the plotting frame size in the code. I'm on a Windows OS platform, and I find if I increase the plot window size in RStudio, this warning is not generated.

**Comment by vn-quant** [comment]
Hello, please help me, how can I increase the plot window size in RStudio or decrease the plotting frame size in the code? I searched in StackOverflow but that did not help
